### ISSUE TITLE
Doc suggestion: coreboot stuff

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#15]
~~There are dozens of posts in the ML related to hardware and coreboot. Maybe systematize those in a doc ?~~

edit: @one7two99 wrote https://github.com/Qubes-Community/Contents/blob/master/docs/coreboot/x230.md

if there's no qubes specific content at all, it's left to decide whether to host here and link in coreboot's wiki, or the opposite

**Comment by one7two99** [comment]
Hello Ivan,

On 04/04 05:08, Ivan wrote:
> There are dozens of posts in the ML related to hardware and coreboot. Maybe systematize those in a doc ?

Yes! please. I would like to see a full example installing Coreboot for a common device like the Lenovo T4x0/X2x0.
In order to simplify the doc I would assume that Qubes OS is the single OS, not covering a dual boot setup.

[799]

**Comment by taradiddles** [comment]
the thing is, I don't know anything about coreboot ! I have a T450s and it doesn't seem to be supported :(

it seems to be a popular topic on the ML though so I thought one of you could add some info (IIRC @Aekez and @awokd replied to some of the ML posts).

Do you know if there are specific instructions when running Qubes with coreboot, or both are independent ? If that's the former then a doc page makes sense, otherwise we can simply add links to coreboot's site/MLs/... (maybe with specific links to hardware which seems to be used by qubes users - x220, x230, ...).

**Comment by one7two99** [comment]
Hello,

Ivan <notifications@github.com> schrieb am Do., 5. Apr. 2018, 20:00:

> it seems to be a popular topic on the ML though so I thought one of you
> could add some info (IIRC @Aekez <https://github.com/Aekez> and @awokd
> <https://github.com/awokd> replied to some of the ML posts).
>
Yes there is a lot of information at several location but I'd like to see
one guide which takes from zero to a full Coreboot installation for a
Lenovo X230.
Most howtos only cover certain parts or left out some details.

I have mainly written everything down for Corebooting the X230. The only
part I am unsure about is, if my Coreboot config file is following best
practices.
Everything else ...

1) hardware shopping list for a raspbeery pi based flash rom tool
2) installing raspbian + flashrom
3) downloading the stock rom
4) extracting binary blobs
5) building Coreboot + compiling a Rom including SeaBIOS.
6) flashing Coreboot
7) reflash with Coreboot rom

... Is covered in my how-to.
Only step 5 is not yet clear and I'd like to know what are the best
settings here.

I'll post the How-to in the Qubes Community Docs.

> Do you know if there are specific instructions when running Qubes with
> coreboot, or both are independent ?
>
I don't know.
It seems there are issues with USB boot under Coreboot, but I don't think
that it makes a difference if you run Qubes or maybe Fedora or another
Linux with Coreboot.

If that's the former then a doc page makes sense, otherwise we can simply
> add links to coreboot's site/MLs/... (maybe with specific links to hardware
> which seems to be used by qubes users - x220, x230, ...).
>
The X220, X230 and T-430 seems to be very common devices and as such having
a detailed how-to would benefit some users and also newbies looking for a
good device to get a reasonable secure system.

[799]

>

**Comment by awokd** [comment]
on step 5, some might say doing grub boot is better than SeaBIOS! I am a fan of coreboot but am wondering if the writeup is 100% coreboot material only, if it might be a better fit for their wiki? Otherwise we could end up with articles like "best office chair to use with Qubes". I think something like "best way to do to a full build of coreboot for x230 and Qubes" could fit here though, like you seem to be suggesting.

**Comment by one7two99** [comment]
Hello Awokd,

awokd <notifications@github.com> schrieb am Fr., 6. Apr. 2018, 00:18:

> I am a fan of coreboot but am wondering if the writeup is 100% coreboot
> material only, if it might be a better fit for their wiki? Otherwise we
> could end up with articles like "best office chair to use with Qubes". I
> think something like "best way to do to a full build of coreboot for x230
> and Qubes" could fit here though, like you seem to be suggesting.
>
Laughed about your "best office chair" ... Nice ;-)
Honestly I think you are right, as there doesn't seem to be anything Qubes
specific in Coreboot except maybe in setting up encrypted boot using
Coreboot with grub.

Still I like to see one article which covers everything, maybe divided in a
section which is modell specific and what is more generic.
The benefit would be that a newbie Coreboot user has a single place to stop
as he only needs to look at his hardware modell.
You might be right that it would make more sense to locate this info in the
Coreboot wiki, on the other side it would also be an advertisement for
Qubes if we can host this info in the community docs.

All Coreboot users should know about Qubes and all Qubes Users about
Coreboot.

[799]

>

**Comment by one7two99** [comment]
Hello,

my first draft of my howto is located her:

.config file for coreboot (after running make nconfig)
https://github.com/Qubes-Community/Contents/blob/master/coreboot-x230-configfile

the howto:
https://github.com/Qubes-Community/Contents/blob/master/coreboot-x230.md

it still needs some editing and information how to connect the flashing
clip to the pi.
but it has already enough information in it to release it.
It covers the following points:

1) what hardware you need to build a bios chip flashing device
2) how to read your current bios chips
3) how to setup coreboot
4) how to extract binary blobs from your own BIOS
5) how to extract vga.rom from your own BIOS
6) how to build coreboot for the x230
7) how to flash the x230

Someone with more github skills has to move the files the right location.
I'll fill in the gaps (wiring) of the raspberry pi/flashing clip and
accessing the BIOS chjips within the next days.

[799]

**Comment by taradiddles** [comment]
nice howto :)

I've moved it (and .config) in `docs/coreboot/` and added a link in the docs' index/readme.

I think I read somewhere that anti evil maid required to update something in coreboot but I can't remember what. If there's indeed such thing it'd be interesting to add it to the howto since it's qubes specific. Maybe we can ask the people on the ML who use coreboot...

If in the end there's no qubes specific content in the howto but you prefer to leave it here, you should definitely add a link to it in coreboot's wiki !

**Comment by taradiddles** [comment]
closing - https://github.com/Qubes-Community/Contents/blob/master/docs/coreboot/x230.md

**Comment by one7two99** [comment]
Hello Ivan,

On 04/15 04:01, Ivan wrote:
> closing - https://github.com/Qubes-Community/Contents/blob/master/docs/coreboot/x230.md

what does this message means "closing" ?
Sorry for asking but I even when using Github for some weeks now I would call my self a beginner.

[799]

**Comment by taradiddles** [comment]
Hi !

I've closed the issue because you wrote the coreboot documentation (thanks!) and I thought the purpose of the issue - reminding about writing coreboot docs - was over. See for instance #11 or #16: they served as suggestion/reminders and I've closed them after documenting each topic.

But please reopen the issue if you feel it's best kept open to discuss further coreboot stuff (I think you can reopen as a site admin - otherwise I'll do it).

Cheers,
Ivan
