### ISSUE TITLE
vpn.md: Fix hang on proxyVM shutdown

### ISSUE THREAD

**Issue by dadigi** [Qubes-Community/Contents#198]
Hi,
I changed qubes-vpn-handler.sh to check for a scheduled shutdown.
This will cause a clean exit of the openvpn down option in case the VM is requested to shut down.
[qubes-vpn-handler.sh.txt](https://github.com/Qubes-Community/Contents/files/9075291/qubes-vpn-handler.sh.txt)

**Comment by taradiddles** [comment]
Hi,
I see the change adds a test for `/run/systemd/shutdown/scheduled` to prevent calling `rc.local` if present.
In theory a shutdown could be scheduled in the future rather than immediately, during which the vpn should still be up - but I've never seen that in Qubes, and if I remember correctly the scripts block cleartext packets so it would be OK to loose vpn connectivity while waiting for shutdown. But more generally I don't understand why systemd wouldn't take care of properly killing anything that prevents a proper shutdown.
As noted in a recent PR (#197) the instructions look quite fragile and would ultimately need a rework (or even a change in architecture, as discussed in issue #103) - but nobody has volunteered yet.
Do you think you'd be able to send a PR with your fix ?

**Comment by dadigi** [comment]
I use a debian-11-minimal-template on Qubes 4.1 for the openvpn-vm.
Without my workaround the shutdown (e.g. via qvm-shutdown) hangs for the default 90 seconds with "A stop job is running for Qubes mis...post-boot actions".

I created a PR with my changes.

**Comment by dadigi** [comment]
Actually the proposal does not make any difference.
Shutdown was faster with my change, because the script always failed on the test command.
Sorry for wasting your time.

**Comment by taradiddles** [comment]
> Sorry for wasting your time

No problem, don't worry !
