### ISSUE TITLE
Examples of template setups, data compartmentalization, data flows, ...

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#21]
IMHO it'd be a nice addition to document various people's way of using Qubes, eg.
- how many templates they use, how they customize them
- what is networked, what isn't
- what kind of data is allowed in specific VMs
- how data may flow between VMs
- pros/cons of having too many templateVMs (disk size, bandwidth for download updates, RAM, ...)
- ...

Obviously there's no one-size-fits-all setup but we could put together a doc with the concensus on best practices, + have a folder with user examples (eg. `partitioning/Chris_Laprise`, `partitioning/Aekez`, ...). This should help newcomers set up something that is appropriate for their needs. Long time users may also learn a thing or two :)

The per-user files could also contain productivity tricks, what WM they use (e.g i3), ...

Related posts:
- https://blog.invisiblethings.org/2011/03/13/partitioning-my-digital-life-into.html
- https://groups.google.com/forum/#!topic/qubes-users/hvGX_Q7gv2o

**Comment by one7two99** [comment]
Agreed, very interesting and basically the most important part in Qubes and
also the hardest to get a good compromise between productivity and security.

IMHO some productivity tricks are crucial to make the decision moving to
Qubes OS as primary OS.
For example one of the most annoying things in Qubes is the lack of
screenshot support within one AppVM.

Creating, editing and mailing Screenshot is a very important part for my
productivity and mainly the biggest reason I have to use another OS/remote
Desktop for this.

I made the pain somewhat smaller writing a
Copy-Screenshot-to-AppVMs-Clipboard Script, but even with this the
productivity impact is to high.

I'll start describing my App/Template setup later.
I think we also need to add a short intro about describing the different
philosophies, separate VMs by trust, vs. separate VMs by applications, vs
separate VMs by contexts (work/private/leisure/..) etc.


[799]

Ivan <notifications@github.com> schrieb am Fr., 27. Apr. 2018, 07:29:

**Comment by taradiddles** [comment]
Yes, that's one of the most interesting documentation this project could provide. Actually this doc suggestion was sitting in my TODOs list for quite some time but I was wondering how to organize the whole topic. I think it'll make sense that we discuss the "best practices" (here or in a team discussion) and have people submit their workflow/productivity tips.

For instance @awokd described his templates, from light to heavy, with 'heavy' being without any internet access ; I have the same setup but reversed: most of my VMs based on my light template don't have internet and are used for banking, very private stuff, etc., while VMs based on my heavy template have internet for daily browsing and multimedia stuff, where I don't have any personal data. The attack surface is of course increased when you have a lot more software, but at the same time I don't see how I'd use my 'heavy' template without internet; I use dispVMs for crappy sites or for opening incoming attachements. It'd be interesting to discuss those - maybe I've missed something important and I'll end up totally revising the way I organize things in Qubes. So - interesting topic indeed !

**Comment by awokd** [comment]
I arranged them that way with an eye towards exploits like https://scarybeastsecurity.blogspot.nl/2016/11/0day-exploit-compromising-linux-desktop.html. If preview/thumbnail handlers aren't installed on an internet attached AppVM, that compromise won't work. You can then run it through tools like making it into a trusted PDF before qvm-moving it to a fat, offline AppVM for viewing so even if that AppVM subsequently gets compromised, it's hopefully contained. Agree on DispVMs for general internet usage.

**Comment by taradiddles** [comment]
IMHO dispVMs are great but they sometimes get in the way of general internet usage: eg. no bookmarks and no saved passwords (which is good and bad depending on what you want to achieve), and they take a while to start. In the end I find myself using my fat untrusted VM's browser most of the time, and I only launch a dispvm when a site doesn't work with a heavily restricted umatrix add-on, or if I know beforehand that the site I have to browse is dodgy.

I've been trying to to find a workaround ; a middle ground solution would be to have a "semi-persistent" dispVM - eg one that doesn't shutdown when its main process is closed, but which would have a "max age" setting after which it is shutdown if no windows are active. Alternatively, a regular VM could be created and then destroyed after "max age" seconds. Either way, the browser's profile would have to be copied to this "half" dispVM in order to have bookmarks and saved passwords, which in itself isn't a good idea (tracking, persistent malware, etc.).

As a side note, @rustybird's [qubes-split-browser](https://github.com/rustybird/qubes-split-browser) is quite interesting when it comes to sharing bookmarks; I didn't have time to test it yet. Note to myself: add this project to doc/README.md

**Comment by Aekez** [comment]
This is a cool idea, it'd definitely be helpful, not only to the Community Collaboration, but also maybe even for the Qubes developers if we can make the data good enough to be useful. 

For example, we could try make a optional small weekly or even a monthly survey based on themes? There are much accuracy to be discussed though, and privacy of users too. But if we can solve those issues, or solve them as far as possible, and we can get enough Qubes users to voluntarily enter surveys on how they use Qubes, then it'd be quite useful imho.

**For example, survey questions for once a year basis;**
How many AppVM's do you have?
How many AppVM's do you use on a daily basis?
How many templates did you make?
How many standalone VM's did you make?
What was for you the hardest part about Qubes after 1 hour of use?
What was for you the hardest part about Qubes after 1 week of use (can be skipped)?
What was for you the hardest part about Qubes after 1 year of use (can be skipped)?
Do you feel the lack of GPU is missing in Qubes? 
-If so, please rate how important it is to you (can be skipped).
-Please pick the primary reason you need GPU (can be skipped).
-Please pick the secondary reason you need GPU (can be skipped).
and many, many other potential questions.

We could for example make a standard one, including general questions like above, and then re-post it once a year. So after, say, 5 years, we start to be able to see how user behaviors changes as well. It is best to construct the survey for once a year, so that its questions doesn't change too much. New questions are less of a problem, since it just means the data-point for that particular question, has a different time-frame. It shouldn't be a problem for accuracy, for as long the developers take this time-frame into account.

There are many dynamics to account for, like different user-groups who is not aware of the survey, or types of user-groups not taking the survey, and other things that make the survey less accurate. And privacy of users needs to be taken seriously too, so it's not easy to just set one up.

Perhaps we can distribute it via the qubes-user mail-group and post to everyone directly, with the Qubes staff's official permission, i.e. once a year? It'd be a win-win-win scenario if done correctly, i.e. it would not only be useful to us, it'd be potentially be useful for the Qubes developers too.

**Comment by taradiddles** [comment]
Hey @Aekez, nice to see you're back :)

> There are many dynamics to account for, like different user-groups who is not aware of the survey, or types of user-groups not taking the survey, and other things that make the survey less accurate. And privacy of users needs to be taken seriously too, so it's not easy to just set one up.

^this. Given the privacy and incomplete audience issues (eg. targeting only ML subscribers) it'll be impossible to interpret the results/trends properly. That's a common problem that other distributions have, and that AFAIK was never solved.

My original idea was to document the setup of "power users" and long-term qubes users. For instance I'm using more or less the same VMs for 2 years but a short discussion with @awokd made me reconsider some of the choices I've made back then.

I was wondering how sample setups could be organized - but given that everybody has different security needs (malware/virus vs privacy vs anonymity) it'd be best to simply document the setups and let people pick ideas. I'm also wondering if listing best practices make any sense. The only important thing IMHO is this phrase from @tasket (from the ML thread I've linked in the OP):

> Qubes is designed so that the biggest factor in maintaining security is always how you divide up your data and workflows between VMs; Choice of template isn't as critical.
vmm-xen-stubdom-linux

And maybe, that obviously the more packages you install in a VM/templateVM, the more you increase the risk of being compromised with:
- privilege escalation, which can potentially be used to attack the hypervisor and/or inter-VM
- malware/virus installation in the VM private volume

**Comment by taradiddles** [comment]
FWIW I've created a `user-setups` folder with a readme and I've documented my own setup - see:
- https://github.com/Qubes-Community/Contents/tree/master/docs/user-setups
- https://github.com/Qubes-Community/Contents/tree/master/docs/user-setups/taradiddles

It's left to see whether this kind of content is OK here (if OK, suggestions on the format, level of detail, etc. are welcome). Otherwise I'll delete it - I didn't loose much time on those, the content is from my personal notes, only had to pretty them up a little bit, so no problem.

**Comment by Aekez** [comment]
> It's left to see whether this kind of content is OK here 

I think it's indeed the most ideal location for it, and it fits right in, imho. It's a good idea, then people can freely upload their own user-setups as well. 

It'd also be interesting to have self constructed diagrams, if the user got some time, like an hour or so, to chart everything up for visual perspective. Maybe even screenshots. As it is said, one picture is worth more than a thousand words. May sound a bit cliché, but I've come to accept it as often true. It'd indeed be interesting if long-term or advanced users started to chalk up their user-setups.

_**For example this one, it's not finished yet, but its a work-in-progress secure Qubes network, shown via a diagram. This carries a whole lot of text and information between the lines, even if its just a simple diagram. Disclaimer: While this isn't relevant to the topic, it may be relevant to point out that the diagram has some critical flaws that still needs correcting.**_


![screenshot_2018-04-26_04-00-20](https://user-images.githubusercontent.com/33869013/39281779-e6fd0a70-48f5-11e8-8aaf-f098c0fbbbcf.png)

**Comment by awokd** [comment]
Closing for now.
