### ISSUE TITLE
Doc suggestion: Restore function in 4.0 to templates restored from 3.2

### ISSUE THREAD

**Issue by awokd** [Qubes-Community/Contents#22]
****Completed document is [here](https://github.com/Qubes-Community/Contents/blob/master/docs/system/restore-3.2.md)****

Problems with restored templates/standalones include:
* can't update
* menu shortcuts don't work

From the mailing list:
~~~
I just spent a good time getting my backuped templates from Qubes 3 to work in Qubes
4 RC3. I'm posting here what I did (roughly) to get it work, in the hope it can help
somebody.

After running qvm-backup-restore, starts a terminal for your VM:

$ qvm-run mytemplate gnome-terminal

In the VM, 

- Rename /etc/apt/sources.list.d/qubes-r3.list to /etc/apt/sources.list.d/qubes-r4.list
   
- Replace mention of "3.2" to "4.0" qubes-r4.list

Now we will import the new GPG keys used to sign the packages.

- Start one of the official template:

 $ qvm-run debian-8 gnome-terminal

In the debian-8 VM:

$ apt-ket exportall > /tmp/keys.txt
$ qvm-copy-to-vm /tmp/keys.txt

Choose "mytemplate" as destination.

In the mytemplate VM:

$ apt-key import ~/QubesIncoming/debian-8/keys.txt

Now enable networking in the mytemplate settings by specifying sys-net as a network VM.

Updates the packages:

$ apt-get update
$ apt-get upgrade

When prompted, choose to use the qubes-r4.list from the maintainer (or merge manually).

Disable network in the mytemplate VM.
Restart.

Now the proxy updates should work again.
Maybe it is necessary to $ apt-get install qubes-core-agent
in the VM after update, not sure.
~~~
This process seemed to work and I was able to install 4.0 updates, but after that I could no longer even `qvm-run <vmname> gnome-terminal`. Not sure it's something easily fixed; didn't make any progress so ended up creating a replacement and using `qvm-copy-to-vm` to copy out the data.

Will close this if nobody has other suggestions, just recording here.

**Comment by taradiddles** [comment]
Is it specific to debian ? Back when upgrading to 4.0rcX I tried to update a restored 3.2 fedora VM with 4.0 packages and it was an epic failure : the VM wouldn't even boot...

**Comment by Aekez** [comment]
> I think I had to set virt_mode back to HVM after restore to get it to boot.

Did you find a work-around with changing virt_mode, or is the issue still there? As for once its booted, I also went the long route and copied everything over, VM by VM (although I did this before PVH was implemented, so I never experienced the PVH issue from 3.2. backups). Moving everything was painfully slow, took better half of a day to do it... 

I also wonder if manually mounting the image volumes may be desired in case there are any Qubes tools conflicts between Qubes 3.2. and Qubes 4.0? I remember feeling very uneasy about bit-corruption of data back when I transitioned from 3.2. to 4.0.

Hopefully we won't see issues like this again with other new major Qubes upgrades. There seems to be a lack of recommendation on how to do this upgrading from Qubes 3.2. to Qubes 4.0 from the developers? or maybe we missed it? I also had my fair share of this upgrading issue, since we all 3 ran into it each on our own, a recommended guideline made by the developers seems like something that might be wanted, preferably as early as possible, i.e. from RC-1. I'm a bit puzzled that I haven't seen many people posting on this issue though, it seems like a problem everyone would run into when upgrading to Qubes 4.

**Comment by taradiddles** [comment]
fyi

https://github.com/QubesOS/qubes-issues/issues/3934

**Comment by taradiddles** [comment]
just tried to update an old fedora 25 standaloneVM I had on 3.2: I didn't manage to get it to a working point :(

steps:
- `dnf update` (without doing an upgrade : only updating f25 packages)
- copy `/etc/yum.repos.d/qubes-r4.repo` from a 4.0 VM
- disable/remove `/etc/yum.repos.d/qubes-r3.repo`
- copy `/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-{stable,unstable}` from a 4.0 VM and import them with `rpm --import`
- run `dnf update` once more ; there was a problem with `qubes-core-agent` ('failed to unpack' or something like that) so I had to install it with `dnf install qubes-core-agent`

after rebooting the VM, trying to run commands with `qvm-run` wouldn't work: `qvm-run` would seemingly hang (ctrl-c needed to exit) without any helpful error message. Killing the VM would then show a "cannot connect to display :0" or something like that, indicating that there was likely a problem with qubes' gui agent. Xen's console log showed that the VM reached the usual login prompt but showed no error about the gui agent.
I had to set virt_mode to hvm and debug to true to get a debug window/console. From there I could see that the `qubes-gui-agent` service was disabled and not running (despite being in `/etc/init.d` too). Enabling it and starting it allowed `qvm-run` commands to run successfully.

The VM then seemed to be functional, but I noticed that sudo wasn't working so I tried to install `qubes-core-agent-passwordless-root`; this failed because the network wasn't configured. `systemctl restart network` didn't help. Something is likely missing but without network connectivity this would require copying rpms from another VM.

Fiddling with the steps described above took half an hour; that's not much but at that point it seemed easier to reconfigure/customize a working 4.0 VM rather than spending more time on updating a 3.2 VM that isn't guaranteed to work properly.

**Comment by Aekez** [comment]
> Fiddling with the steps described above took half an hour; that's not much but at that point it seemed easier to reconfigure/customize a working 4.0 VM rather than spending more time on updating a 3.2 VM that isn't guaranteed to work properly. 

That's the approach I usually go with as well, sometimes I write down the apps I install in a particular AppVM, however it gets a bit tiresome to keep the habit. Maybe with some more effort the habit can be more easy to maintain though.

This got me thinking, perhaps this could work with making a script that can install all the packages for a particular template, so when adding it to a memory list, then it's also at the same time added to a script that is easy to click-to-install-everything? For example if the script is already there, and the script can be executed from a random AppVM to apply to the specified template name (with no Qubes-RPC changes, just clicking "ok" on the popup).

**Comment by awokd** [comment]
I tried pretty much those same exact steps @taradiddles and eventually went with new templates too.

@Aekez, package management like that sounds like a job for SALT and the dom0 management integration the Qubes team is working on!

**Comment by taradiddles** [comment]
being a bit stubborn I tried the following and it seemed to work:

after the last 'dnf update' step of my previous post:
- got a list of rpms installed on a working (minimal) 4.0 VM with `rpm -qa | grep ^qubes | sed -ne 's/-[0-9].*//p' > rpms-4` and copied it to the VM being updated
- installed missing packages with `sudo dnf install $(cat rpms-4)` (existing packages are skipped)
- enabled the gui agent with `systemctl enable qubes-gui-agent`

I didn't need to set virt_mode to hvm this time.

notes:
- the last `dnf update` step seemed redundant with  `dnf install $(cat rpms-4)` but skipping it resulted in a totally broken VM: I had to run `dnf --best --allowerasing` because of conflict complaints, and after a reboot `/` would be read-only - go figure.
- my imported 3.2 VM was in PV by default, maybe that's because I've imported it under 4.0rc3. I've set it to PVH and it works OK.
- starting apps from the qubes menu works, ie. no need to start them from dom0 with `qvm-run`
- `qvm-copy` doesn't work but I'm pretty sure it's because f25 is old and `qubes-core-agent` isn't updated to reflect the special character change (`_` to `@`)
- if these steps are transformed into a user doc, the `rpm-4` list below should be stripped from rpms that were already installed or which are automatically pulled as dependencies.

rpms-4:

~~~
qubes-core-agent
qubes-core-agent-dom0-updates
qubes-core-agent-nautilus
qubes-core-agent-networking
qubes-core-agent-network-manager
qubes-core-agent-passwordless-root
qubes-core-agent-qrexec
qubes-core-agent-systemd
qubes-db
qubes-db-libs
qubes-db-vm
qubes-gpg-split
qubes-gui-agent
qubes-kernel-vm-support
qubes-libvchan-xen
qubes-usb-proxy
qubes-utils
qubes-utils-libs
qubes-vm-dependencies
~~~

**Comment by awokd** [comment]
Nice work, @taradiddles ! I thought it was hopeless, I spent hours on it.

> stripped from rpms that were already installed or which are automatically pulled as dependencies

What do you mean by this? Wouldn't the `dnf install $(cat rpms-4)` step just skip packages from that list that were already installed?

**Comment by taradiddles** [comment]
Thanks :)

> What do you mean by this? Wouldn't the dnf install $(cat rpms-4) step just skip packages from that list that were already installed?

Yes it would (and did). It's just that the list isn't "pretty" for a doc and could probably be reduced to only a few rpms: for instance `qubes-vm-dependencies` likely pulls most of the other qubes* rpms.

**Comment by awokd** [comment]
Got it. I should still have a backup somewhere of my 3.2 templates so will give this another shot and try to simplify and document!

**Comment by taradiddles** [comment]
I still have a backup from my test VM, so I should be able to easily find out which rpms are pulled as dependencies if you want.

**Comment by awokd** [comment]
No need; that part is easy enough to figure out, but please keep that backup handy for a couple weeks or so to be able to test against the document?

**Comment by taradiddles** [comment]
OK !

**Comment by awokd** [comment]
Work notes:
- After restore 3.2 template, confirm PVH and kernel is set
- `qvu-run <templatename> gnome-terminal`
- copy `/etc/yum.repos.d/qubes-r4.repo` from a 4.0 VM
- disable/remove `/etc/yum.repos.d/qubes-r3.repo`
- copy `/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-{stable,unstable}` from a 4.0 VM and import them with rpm --import
- `sudo dnf update`

(to be continued)

**Comment by awokd** [comment]
Created https://github.com/Qubes-Community/Contents/blob/master/docs/system/restore-3.2.md. Added link at top; closing.
