### ISSUE TITLE
Contact / content migration

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#256]
Relevant issue: #257 

- Ack / NAck for migrating your contribution from GPLv2 to CC BY 4.0.
- Nack - if any - for migrating your contribution to the forum (if so, it would help to know the reason but it's obviously not required).
- your forum username, if you're a forum member and want to be notified when the migrated guide is edited on the forum.

**Comment by jamke** [comment]
Thank for your work!

1. Please replace Ack and NAck with something translatable for non-native speakers. The post is big and such non-common reductions probably should be avoided especially for this crucial places in the text. 

2. I agree to license change from GPLv2 to CC BY 4.0 and moving to forum anything of my contribution to `qubes-docs` and `qubes-community`.

**Comment by taradiddles** [comment]
Thank you.
I've updated the post with "OK / Not OK" and changed the wording of the "NAck" for migrating to the forum; I hope it's better (I'm not a native English speaker btw) - no problem to change things further!

**Comment by GWeck** [comment]
I agree to license change from GPLv2 to CC BY 4.0 and moving to forum anything of my contribution to qubes-docs and qubes-community.

Note, however, that the documentation [part ](https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows.md)concerning the installation of Windows and Qubes Windows Tools is in the process of moving from the community documentation to the official qubes-doc repository, currently waiting for review in [PR #1286](https://github.com/QubesOS/qubes-doc/pull/1286).

If there are any questions, please feel free to contact me.

**Comment by taradiddles** [comment]
Thank you @GWeck !
Re- your PR #1286: noted (I saw it some time ago - that's why I mentioned "with the exception of [...] pending PRs to the official qubes-doc repository.)

**Comment by aronowski** [comment]
- I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
- I'm OK with migrating my contributions to the forum
- my forum username: [**aronowski**](https://forum.qubes-os.org/u/aronowski/)

**Comment by 3hhh** [comment]
- I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
- I'm OK with migrating my contributions to the forum
- I'm not a big fan of the decision anyway.

**Comment by taradiddles** [comment]
> * I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
> 
> * I'm OK with migrating my contributions to the forum

Thank you.

> * I'm not a big fan of the decision anyway.

If that's not too much asking, could you elaborate? (privately via email is OK of course). Eg. is it the platform change? And/or that posts will become wikis? (if so it's possible to restrict editing by "user level" - that's something we weighted for "critical" docs but haven't settled on yet). Knowing what bothers you would really help.

**Comment by 3hhh** [comment]
On 6/1/23 09:44, Ivan wrote:
>> * I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
>>
>> * I'm OK with migrating my contributions to the forum
> 
> Thank you.
> 
>> * I'm not a big fan of the decision anyway.
> 
> If that's not too much asking, could you elaborate? (privately via email is OK of course).
I'm simply not a big fan of the forum. I agree that it'll probably be more accessible for most regular users, but I also consider it less interesting for the more technical users (the signal-to-noise ratio is just not good enough). The technical users however are the ones creating the content. So my guess is that content consumption may go up at the cost of less quality content creation. It's just a personal guess though.

**Comment by taradiddles** [comment]
> I'm simply not a big fan of the forum. I agree that it'll probably be more accessible for most regular users, but I also consider it less interesting for the more technical users (the signal-to-noise ratio is just not good enough). The technical users however are the ones creating the content. So my guess is that content consumption may go up at the cost of less quality content creation. It's just a personal guess though.

Thank you for clarifying - I do understand your concern. There *are* pretty good technical guides in the forum, but we're well aware (forum admins included) that the forum's content isn't as consistent as the docs here.

The decision to consider migrating resources to the forum wasn't taken lightly but in the end it seemed to be most appropriate, in order to prevent all the work/time that contributors have put into writing quality documents from being lost as instructions slowly but surely become outdated (with some exceptions of course, thanks to a few active contributors).

FWIW, the trigger for this whole migration thing was [this PR](https://github.com/QubesOS/qubes-doc/pull/1314): the doc's topic is popular but nobody has ever contributed any updated instructions, yet there are quite a few posts in the forum with updated 4.x policies. I'm also to blame as I'm the doc's original author and should have updated it when I switched to R4.x but in the end it's a community effort. Had the doc been in the forum, I imagine that someone would likely have posted a short comment with updated instructions, or - best case - would have updated the doc/post itself (*).

Now - one issue (still TBD) is whether to have all documents editable by anyone, or restrict some documents to be editable only by people with a given reputation level (the latter may alleviate your concerns). Also, the documents will be migrated into a specific category - they won't be random posts here and there - so they'll be easy to find, especially with Discord's tagging feature and documentation plugin: that will make them way more easy to find than our monolithic index.
Lastly - you may stick only to the "guides" category to avoid the other categories' "noise" (btw, are you registered in the forum?).

(*) It's always been my opinion that git was too involved for contributing - it's a 2 edges sword: on one hand people have to be *really* motivated to contribute stuff, hence a usually higher quality. On the other hand it's far too time-consuming to submit even short, but helpful, contributions.

**Comment by SvenSemmler** [comment]
@3hhh it might surprise you but I'm not a fan either personally. I hoped it would sort itself out by the more advanced users continuing to use qubes-users while at the same time having the 'more accessible' solution in the forum. The signal-to-noise ratio is awful (sometimes). Like other moderators I am doing my best to keep it at bay, but it's a bit like fighting the tide. We've recently expelled some offenders and it has calmed down a bit.

About the quality of the content: we will employ tags to signal high quality reviewed content and selected guides will likely be linked from an index page on the project's website. Nevertheless the good will be stored in the same place as the questionable and we'll have to work out ways of signalling to the reader which is which.

Other than that the respective category is just another place to host. One doesn't have to be logged in to read and if there are some who do not want to create a forum account to contribute I am sure we can find ways to make that work: send the contribution for discussion to qubes-users and I or others can post it then into the forum with proper attribution.

Regarding edits: there is a history of who changed what and mistakes / vandalism is easily detected / mitigated. We might form a group of 'guardians' who subscribe to notifications for any changes to those wiki posts, so unwelcome changes don't stay up very long. If that fails, we can raise the trust level required for edits and have contributors below this level submit their changes as comments to be then applied to the wiki post by someone with TL2.

In general I want to trust the positive spirit of the community and hope it won't be an issue, but we can handle it if it turns out to be one.

**Comment by imme-emosol** [comment]
- I'm OK with migrating my minor contributions from GPLv2 to CC BY 4.
- I'm OK with migrating my minor contributions to the forum.
- I'm also OK with both being and not being mentioned, or combinations thereof :)
Don't have an account, if i remember correctly.

**Comment by techge** [comment]
* I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
* I'm OK with migrating my contributions to the forum
* Mentioning my (minor) contributions is not necessary and if there still is an account under my handle I won't use (this one) anyway.
* I'm not that big of a fan of the decision, because of similar reasons as 3hhh. Yet, I know and can see that there was some thinking done and I am open to give it a try.

**Comment by kevinjohna6** [comment]
- I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
- I'm OK with migrating my contributions to the forum
- forum username [kevinjohn](https://forum.qubes-os.org/u/kevinjohn/)


I have some feedback on the migration, but its mostly just my personal peeves/preferences:

Having to create another account (or accumulate reputation) often dissuade me from contributing outside of github/stackexchange. Maybe federated login would address this for me.

I see the value in unifying all qubes discussions/knowledge to the forums, but I think that maybe a dedicated MediaWiki style wiki (in the same manner as Arch/Gentoo) would be ideal to encourage contributions.

**Comment by taivlam** [comment]
* I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
* I'm OK with migrating my contributions to the forum
* Forum username: [`taivlam`]

**Comment by ddevz** [comment]
- I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
- I'm OK with migrating my contributions to the forum

My only reason I would have been against putting it on the forum would be if putting it there would cause it to be removed from the search engines indexes, but it seems that the qubes forum now shows up in the indexes.

**Comment by lubellier** [comment]
- I'm OK with migrating my contributions from GPLv2 to CC BY 4.0
- I'm OK with migrating my contributions to the forum
- my forum username: ludovic
