### ISSUE TITLE
doc for shrinking volumes in 4.0 ?

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#37]
fyi I've replied to a post in the ML about shrinking volumes (post [here](https://groups.google.com/d/msg/qubes-users/QV5v2dOQDE0/y-5aVORLAQAJ)).

I'm wondering if those instructions should be here (if yes, where ?) or if it's better not to document them since the probability of loosing data is quite high.

**Comment by Aekez** [comment]
It looks like it could be helpful to certain situations despite the risk? But it's an interesting catch-22 scenario you're presenting. Perhaps a solution could be to place a big warning, so that users can decide for themselves if they want to apply the shrinking of volumes or not, weighing between their own needs vs. risks, solving their own catch-22?

Maybe the doc could include a recommendation to make a backup with qvm-backup, since any system without any means to create backups (if not enough drive space or no external drives available, etc), then the user is probably gonna loose that data at some point anyway.

Presumably if taking backups, then the only risk left would be slow incremental bit-rot that doesn't stand-out clearly, but caused hidden damage.

I believe when it comes to files and folders, etc. that there are some scripts floating around on the internet to check hash-values of multiple files/folders, maybe this can be included too to the backup approach? So if the hash values of said files is different after changing the size of the drive volumes, then the user knows bit-corruption occurred.

Do you happen to know any scripts or methods that can run sha256sum (and similar) on multiple files/folders?

**Comment by awokd** [comment]
There used to be [instructions](https://github.com/QubesOS/qubes-doc/blob/341a578f9bf8312739d6fe17345c6e2ae010b860/configuration/resize-disk-image.md) in the official docs to shrink volumes under R3.2, but I pulled them per [Marek's comment](https://github.com/QubesOS/qubes-doc/pull/561#discussion_r166616298). Maybe here would be a better home for them?

**Comment by taradiddles** [comment]
`qvm-create` + copying files is indeed less risky, but isn't it only applicable to AppVMs ? How to resize the root volume of templateVMs or the root/private volumes of standaloneVMs ?

> Maybe here would be a better home for them

probably :)

**Comment by taradiddles** [comment]
@Aekez 

By experience either a resize fails right away, or it works; you don't loose files later on with "bit-rot".
Otherwise yes, a big fat warning about backuping data would be required. I almost never use `qvm-backup` except for long time backup storage; `qvm-clone` should be fine for quickly backuping a VM before messing with it. Alternatively, snaphots can be used but the doc is a bit scarce (another suggestion for a doc BTW: QVM LVM storage and operations...).

> Do you happen to know any scripts or methods that can run sha256sum (and similar) on multiple files/folders?

generate:

~~~
find . -type f -exec sha256sum {} \; > sums
~~~

check:

~~~
sha256sum --check sums | grep FAILED
~~~

**Comment by awokd** [comment]
Wouldn't recommend relying on snapshots for protection on a resize operation. Too many ways a recovery could go wrong. Clones and backups should be safer.

**Comment by Aekez** [comment]
I'm curious how we can improve this though, for example while I agree it cannot yet be relied on, snapshots would for example have saved my last 1-2 weeks of data since the last time I took a backup. It might be ideal to combine a few different methods to be safer, and make a priority tree of sorts (trust backup before snapshots, but if backup fail, go with snapshots, kind of hierachy), unless snapshot formats can cause damage too or be bad in some different way?

@taradiddles 
Awesome, I'll have to give that script a try soon!

**Comment by Aekez** [comment]
I'm wondering if its possible to have more BTRFS partitions on the same drives though, for example would it cause strain on the drive? Could it cause bottle-necks, i.e. like what could hypothetically happen on different data-speed drives? 

If it works though, it would be quite interesting for laptops with only a single drive. It shouldn't be good on laptops with 2 drives though, since it would actually make it a bit worse at no benifits? Given the problem with 2 drives is that if one drive fails, then copying all the data from the working drive over to the new clean drive might cause the second drive to fail (given the stress it induces). And while it seems unlikely, it's happening here and there in the wilds. So 2 drives might not be enough for all scenarios, 3-4 drives is probably the most safe for BTRFS Raid 1, though that's still even fewer drives than the minimum safety for other software/hardware raid layouts. So since the data is probably safe with 2 drives on BTRFS, the risk is that the last working drive might die too on sudden heavy work-burden on copying everything to a new clean drive. So it might only be an idea worth perusing for laptops with a single drive.

If I'm not mistaken, the second+ drives (or partitions on same drive if that works) are much less active too, so it might not become a bottleneck issue?

**Comment by Aekez** [comment]
To be clear, the resize (increase) was changed in the window GUI, rather than the qvm-* commands. From 2GB default to 40GB private storage. Some 120GB free space on a fresh'ish Qubes install. It happened a while ago, but I only had time to check why the AppVM didn't work now today.

**Comment by taradiddles** [comment]
I never used btrfs so I can't comment.

Re- "bit-rot": I never noticed any file corruption since I stopped using floppy disks (!), despite copying terabytes of data over and over on a variety of OSes, filesystems and off-the-shelf hardware without ECC memory. Note that file corruption != failing device - I had a fair share of failed sd cards, usb memory sticks, and whatnot. So IMHO "bit-rot" on live systems is a non-issue, by experience the only important thing is to have redundant up-to-date backups. YMMV, of course.

Re- snapshots: they're only useful for short term rollbacks ; @awokd is right that they shouldn't be used backup purposes (and anyway they're pretty much useless with the current default of 1 snapshot).

**Comment by Aekez** [comment]
oh well, bi-rot is a hypothetical enemy that cannot be seen, so it's really hard to not worry about it. But it's ensuring to hear that you never encountered it all this time. I wonder though, say for example if you take 100 people like you, how many have experienced it, and how many hasn't? For example say 5% or 10% have encountered it, but the rest has not, then it might anecdotally be correct, but statistically incorrect. In that way it can still be a threat, even if you're right. But it's an invisible enemy, it's easy to be worried about it without any real anchor in reality, that I do fully agree with. I just think we need to be careful still, especially as hardware chips gets smaller and smaller, and more error-prone, especially to radiation from the environment, when it becomes this small and compact. Also the more files we have, the greater and greater the risks become too. All I'm saying is that we probably shoulnd't ignore the potential of git-rot, but you're right too that I might be too concerned.

About the snapsnots, please re-read, it's not what I said. I never said snapshots should be used as backup, my point is that snapshots are great the times backup fails you. I just gave an example from my own recent experience where I would not have lost my data between now and my last backup (once a month) if I had used snapshots (despite of actively using backups). Those data in the 1-2 weeks are lost, and it's honestly a hassle to run backups daily, so I do not think that snapshots should be ignored. While snapshots cannot be used as backup, at least they may be the second security once backup fails you, or you loose important data between the time of loose and point of backup.

**Comment by taradiddles** [comment]
"bit-rot": maybe I'm lucky not to have experienced live corruption but IMHO if it happens this shouldn't be a problem if you have the proper backup policy and you keep an history (versioning) of important files. ECC memory and whatnot will help but they'll never cover 100% of the corruption cases (think of obscure bugs in a filesystem).
For instance I backup my not-so-important-but-bulky media files on a NAS, my a-bit-more important-but-still-bulky files on a NAS + external HD, and my very-important files on NAS + 2 or 3 USB memory sticks (checksuming is done by rsync).

snapshots: I see what you mean but I still think that they're totally useless for more than very short-term rollbacks/backups: I don't know how much time you stop/start your VMs, but if you're like me you'll have started them at least 4-5 times during a 2 weeks window. If I'm not mistaken a new snapshot is created at each VM start, which means that to avoid the data loss you encountered you would have needed to set the default number of snapshots to at least 5. Which - again if you're like me - means that you would quickly run out of disk space.

**Comment by Aekez** [comment]
<br />

**Looking back on the post, it became much bigger than I intended.... I apologize if it overwhelms having to read it all, especially if you're busy. In which case, just skip where you feel like skipping.**


<br />


To some extent yes, but bit-rot are silent data-corruption that are scary exactly because they travel in backups too (and not just in the live system). Even with checksums, if they were at any point not stored securely or was processed wrong in RAM/CPU, then bit-corruption can happen even if using proper NAS / hash-check systems, etc. especially on laptops which are harder to protect from bit-rot. That's what make them scary, there is no end-to-end protection against bit-rot, we can only minimize the risk, and they become more frequent the more data we have, the larger our files is, and the longer we keep them, as well as changing technology safety and environment effects.

Okay apologies if I go to some extremes in some of the examples below, I agree that we need to find a realistic reality, so a middle-ground must be found somewhere. I'm pushing it a bit over the middle-ground on some points, and hopefully we can bounce-back to the realistic middle-ground.

For example lets say bit-rot happen to destroy your important family pictures or video/audio recordings (the larger a file is, the more risk for bit-rot, the more files you have, the more risk of bit-rot, so the risk grows as we horde more data, and both is growing a lot in recent years among private people), flips an important number in your data excel data-arc, or things like these, which you might not discover before weeks, months, or even years or decades later, for example that old family picture you got in your backups, was hit by bit-rot, but because bit-rot are silent, we almost never discover them before they reach into our backups. Also files get bigger and bigger too, photes, videos, all take up larger and large space, and is therefore more prone to bit-rot (surface area). And then there is the joker with new technology that might get too small on nano-scales, which makes them more unreliable, will these come to market? What happens if a large solar-storm hits like the one that hit us back in 1859. The suns cycle is roughly 13 years or so, eventually we'll be hit by one of the large solar-storms again, will this affect our sensitive data drives/backup equipment? For example will we even realize before it traverses into our backups?

The problem then is bit-rot travels in backup solutions too. The irony is that the scenario of running out of disk space is also an issue with backups and bit-rot. For example, how many backups do you need to keep storing before you find a copy which wasn't affected by the bit-rot that happened a long time ago? And then the problem becomes if you still have all those old backups, especially if you don't discover the bit-rot before years has passed on an important file.

<br />


**About the snapshots**, leaving the topic of bit-rot, I agree and see your point with drive space, it's a problem.
There are solutions though, but they are not perfect, and should probably be seen as overlapping solutions that create a safety-net below the other safety-net if the first one breaks (but at the same time not cause too much hassle to maintain the safety-nets). 

What could be done for one safety-net, is to separate the Qubes system from the AppVM and maybe the Template data too (which is much more easy in Qubes 4 now), and then keep them on a separate volume, which takes snapshots less frequently, but keeps more versions. For example once a day instead of every time restarting them (could be changed to ones data-safety needs). If small enough AppVM data sizes and with decent size drives, then it isn't farfetched to keep many snapshots at every restart, for a good while back. For example some AppVM's are much easier to snapshot than others due to their small size, but contain important data.

There is also the possibility of making a partition for small AppVM's (containing docs, work, small sized important data, etc.), which sits on a partition that gets much more frequent snapshots, than another volume, which keeps all the heavy AppVM data VM's and is less frequent snapshotting.

There is also the possibility of dynamic snapshotting, for example for every 10 snapshots, 9 are deleted and only 1 is kept. This isn't reliable either, but it has another strong point, which is that it can preserve more data in a different way when full backup failed (or like most people, simply not doing backups, which we must remember too imho). This is of course not a fully reliable method either, but a method to use on less important data, or in addition ontop of othjer methods for important data.

There are many ways to go about snapshotting, but generally I'm not arguring to reach perfect protection (that's indeed impossible in todays tech level). I know it might sound like I'm reaching toward the impossible idealistic data-safety when I also talk about bit-rot), but I am thankfully not an extremist in that regard, I know that there must be a balance to reality too, and what can be done on daily basis in a realistic fashion, in relation to risk. It's just that I believe whatever risk can be reduced with affordable effort, I think is well worth perusing. The extremist pursuits? Don't worry, I know it's unrealistic to pursue the extremist solutions, I'm not going there with data-safety, I never have :)

Talking about these things, is very different from putting it into practice, but not talking about it I think is bad too, otherwise we might not discover some new ways to go about data safety at minimized effort.

**Comment by taradiddles** [comment]
I've read the whole post :)

bit-rot: I get what you say but this isn't specific to qubes OS, not even to linux. I don't see any solution except sticking to a well defined backup procedure with multiple backup and comparing checksums on a regular basis.

snapshots: the logic(s) you suggest would be better done (IMHO) with user scripts using low level LVM tools. That said the  Qubes snapshot implementation could be improved to keep snapshots until some disk space quota is reached, after which older snapshots are replaced by newer ones.
