### ISSUE TITLE
workflow #1 - "github issues to PR"

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#6]
This issue describes the "issues to PR" workflow, how to use it from a regular user's standpoint, and shortcomings. The text of this post should be updated/edited to reflect changes arising from comments.

**edits:**
* Mar 17: edit TBD / agreed on everything in one repo. + change instructions url
* Mar 14: user guide content moved to md file
* Mar 13: revised text, no more wiki, moving to github issues, they don't require git proficiency either, and that's what this workflow is about

---

#### workflow
TBD
- a regular user creates an issue with content/suggestion/... in the qubes-community repo
- if needed, initial discussion about the content happens in the issue
- if the issue is worth it, an admin creates a PR
    - directly to the official qubes-docs repo
    - to qubes-doc-community-fork
    - to qubes-community (doc or not doc)
- ... and then closes the issue with a link to the new PR.
- further discussion - if any - happens in the PR.
- if the issue is not deemed fit for inclusion in any of the repos, the issue is closed indicating the reason of the content/suggestion/... rejection

#### TBD
- while I don't care about attribution and credit, some people may. Either make it clear in the user guide that there aren't attributions, or if there are, find out how to keep them.
- ~~should there be a separate repo dedicated to  handle those issues - so that they aren't mixed with other stuff if we expect they may be of lower quality - or is tagging enough (tagging requires time). [ I'm for having everything in qubes-community ]~~
- user guide / see https://github.com/Qubes-Community/Qubes-Community.github.io/blob/master/README.md

#### reasons for not using github's wiki
1. github's wiki is crap; there are no simple notifications mecanisms when new content is posted. So one would have to regularly go through the page(s) to see if anything changed. But that's probably fine if there are only 1-3 pages. An alternative would be to use a paid hosted mediawiki (saw plans at bluehost for 3USD/month - no problem paying that if needed).
2. no PM to users - see [here](https://webapps.stackexchange.com/questions/29197/any-way-to-contact-a-user-on-github) and [here](https://stackoverflow.com/questions/12686545/how-to-leave-a-message-for-a-github-com-user#12687679) so the user **must** have entered his email in his profile.

**Comment by taradiddles** [comment]
Actually we could get rid of the wiki as a whole and only use issues instead, since they don't require any git knowledge - which is what this specific workflow is about.

Using issues would solve almost all the shortcomings described in the OP.

**Comment by Aekez** [comment]
That's an interesting idea, at first I'm a bit torn between them, but you're making some good points, it's indeed crap... I end more and more to lean up towards using issues instead of wiki's as well. It also feels more "work in progress" like until it becomes either an official qubes doc or community guide. 

Some loose thoughts.
- Maybe we can also still use the wiki pages as locked non-editable content, so they can't be edited, and then copy/paste issues as they are finished into a locked wiki page (that only moderators can do), and then close the issue as it's finished. 

- As such, this could even solve the new pages to send to the qubes doc's? Edits of existing qubes doc pages might be a bit more tricky to do via issues though, but for something like that it shouldn't be holding them back, editing qubes doc pages would require some skills at least, so it wouldn't be too much to ask to copy/paste the qubes doc pages content to be edited in the issue. Maybe a short guide on how to do that for those still unsure on what to do. It also means we can reduce a repository by one and only keep a forked repository, rather than a clone and a forked repository, but drawback then seems to be how to enforce a locked wiki if the locked content is universal to the entire repository and can't be micro-managed.

- Maybe we could use the website to publish anything finished in the issue tracker. That way we can get rid of the wiki altogether?

**Comment by Aekez** [comment]
@awokd 
I'm a bit tempted to troll awokd and say we now have a reason for a blog, but I better not ;3

**Comment by awokd** [comment]
Delete wiki = even simpler = I'm onboard

**Comment by taradiddles** [comment]
updated OP to reflect wiki->issues workflow.

**Comment by Aekez** [comment]
How are we going to put this into practice though? one single repository for everything, including the doc/guide issue drafts? are we gonna use it for doc drafts as well? and also the question if we split it up in more repositories, how many do we need? can it be done without being messy in a single repository? 

It worries me a bit if it becomes a bit too messy with everything cluttered together, but too many repositories can also be messy on it's own. So it seems we need a good balance between the two? or should we try see if we can put everything in a single repository?

**Comment by awokd** [comment]
@taradiddles This seems reasonable to me. Agree on single repo. I created a `doc-contrib` label and edited the user guide so people can self-tag if they want to contribute something (or we can too).

>    to qubes-community (doc or not doc)

Do you mean for scripts for example?

**Comment by taradiddles** [comment]
> Do you mean for scripts for example

Yes, or perhaps link to scripts. For instance someone could submit an issue like "hey I have project X at url Y, feel free to link to your links" ; much easier for the user than forking a repo, adding the link, creating a pull request, and more or less the same time for an admin to review the PR or edit the page directly.

The thing is, I'm not so sure about how this workflow integrates with the 2 other ones - there's clearly an overlap.

And BTW feel free to edit anything I've created, even with significant changes.

**Comment by awokd** [comment]
I don't see it as an overlap. This workflow is for Issues -> Content (wherever it ends up). In case we want to upstream them, this workflow might feed into others depending on its destination, but doesn't necessary overlap.

**Comment by taradiddles** [comment]
I meant that the instructions of this workflow overlap with the other 2 workflows' instructions (particularly workflow 3 - content/PR to community).

**Comment by awokd** [comment]
Can we refine this issue to just cover the intake side; i.e. the "Issue -> PR" portion? So it's:

Issue -> PR -> workflow 2 (qubes-doc upstream)
Issue -> PR -> workflow 3 (for content intended for the community repo)

Workflow 3's input could always be a PR, whether from this process or a directly submitted one.

**Comment by taradiddles** [comment]
> I created a doc-contrib label and edited the user guide so people can self-tag if they want to contribute something

Are you sure regular users can tag ? I can't tag my official qubes issues, and [this github doc](https://help.github.com/articles/about-labels/) says "To create, edit, apply, or delete a label, you must have write access to the repository"

**Comment by Aekez** [comment]
I think the tagging might be related to the repository permission system? So people need to be a part of a team in order to tag? In general it seems we have very little flexibility with permissions too, maybe that's in the paid github package?

I like the idea of having all input in a single repository, then moderators can help distribute it to the right places. It makes it very simple for everyone, and we can more easily manage it. For example if people say if it's for the Qubes doc's, Community guides, or if they are documenting their script for example, or maybe if we have a closed wiki, an issue request to have an moderator put the page into the wiki, or changing the wiki. In a sense that way we can keep a wiki too. Question then also is whether a wiki is pointless if we use websites anyway. Can wiki and websites be merged into a single system?

In general it might also be best if only moderators can tag? So we avoid clutter and miss-tag's that becomes hard to keep an overview of as the amount issues grow over time? For example if the person making the issue says it's for the Qubes doc's, or if its a script or guide, etc. then moderators can tag it for them?

**Comment by awokd** [comment]
No, not sure they can tag their own issues, was an assumption.

Added a minor edit about submitting an issue on the landing page.

Think we resolved to delete the wiki above.

**Comment by taradiddles** [comment]
wiki: indeed, no more.

tags: OK; most likely users can't self-tag then

landing page: you can change whatever you want. I'll try to add the instructions for workflow 2 when I have a bit more time.

**Comment by Aekez** [comment]
indeed, but what I was thinking is whether closed-wiki's only modified by moderators can serve a small purpose. As we discussed the issue tracker vs. the wiki, and indeed I agree the issue tracker is superior as well. But what I mean here is rather a wiki to put forward content, i.e. can wiki's be used as a means to forward a website page more efficiently? or should website pages strictly be used for this purpose? I agree wiki's might not be ideal here, but what I'm wondering about is whether wiki's can be used as a webpage content page, i.e. making it faster and more efficient to make new sub-webpages. I'm not pushing for this suggestion, I'm only exploring the possibility here.

**Comment by awokd** [comment]
Let's consider the wiki a done discussion and move forward, ok? If we keep vacillating we'll never get stuff done. If the website approach appears to be too cumbersome later on, we can revisit the wiki in a new issue.

**Comment by Aekez** [comment]
well I don't mind that, if anything all I'm saying is to keep the door a bit and slightly open to other alternative use-cases for the wiki, I'm not suggesting to do it now. Having the wiki in the back-hand for use-cases where it might make good sense to use it, for example, might not be bad to have. So all I'm saying, is to be open for other alternative use-cases, in case we'll need it, rather than ban anything wiki, absolutely.

**Comment by awokd** [comment]
Sure, any decisions we make now can be revisited at some point in the future if it becomes necessary, but let's spend our time on implementing them instead of rehashing them once they are made.

**Comment by taradiddles** [comment]
I think we agreed on this workflow. closing the issue then.
To keep the workflow steps visible I've added them to contents/worfklows.md
