### ISSUE TITLE
opening-urls-in-vms outdated

### ISSUE THREAD

**Issue by neowutran** [Qubes-Community/Contents#71]
https://github.com/Qubes-Community/Contents/blob/master/docs/common-tasks/opening-urls-in-vms.md 

1: The RPC policy syntax is outdated. Instead of ``$xxxxx`` it is now ``@xxxx``
( https://www.qubes-os.org/doc/rpc-policy/ , https://www.qubes-os.org/doc/qrexec/#qubes-rpc-administration )

2: A part of the page is already described in the doc ``https://www.qubes-os.org/doc/disposablevm/#opening-a-link-in-a-disposablevm-based-on-a-non-default-disposablevm-template-from-a-qube`` 

3: Some part are about unsupported qubes version ( https://github.com/Qubes-Community/Contents/blob/master/docs/common-tasks/opening-urls-in-vms.md#using-named-dispvms ) 

(4: an information that is not inside the page but is inside the official doc: To run something inside a disposable VM based on a specific disposable vm template, the command is ``qvm-open-in-vm @dispvm:DVMTEMPLATE`` )

**Comment by awokd** [comment]
@taradiddles, you still out there?

**Comment by taradiddles** [comment]
@awokd - yes, still around but not spending time on qubes stuff. That said I'll check/test the OP's remarks and I'll update the doc (thank you @neowutran for taking the time to send your remarks).

**Comment by taradiddles** [comment]
@neowutran:

> 3. Some part are about unsupported qubes version

It's been some time since I last kept track with changes with dispVM stuff but I don't see what's unsupported (I use that setup every day) - can you elaborate ?

Remarks 2 and 4: they kind of overlap ; I've added a link to the official doc (which I wasn't aware of when I wrote the doc - no idea when it was created, the history begins in last May with a rename from adw).

for info the changes are visible at https://github.com/Qubes-Community/Contents/blob/issue71/docs/common-tasks/opening-urls-in-vms.md ; I see you're used to git/PR, feel free to send PRs if you'd like.

**Comment by neowutran** [comment]
3: I tested it and it work : ) 
I am just thinking that is line is not needed anymore ``As of Qubes R4.0, it is impossible to "name" a dispVM: opening a URL/file in a standard dispVMs will always start a VM with a 'dispXXXX' name (eg. 'disp1234').`` since Qubes R3.X is unsupported. 

Also, a thing that I had a hard time to understand ( https://github.com/QubesOS/qubes-issues/issues/5235 ) is that ``@dispvm`` means: DisposableVMs based on the Default DisposableVM Template. (And not: any DisposableVMs )

**Comment by neowutran** [comment]
Seems all good to me :)

**Comment by taradiddles** [comment]
I've merged the changes. Thanks !
